### ISSUE TITLE
Open vote sites in new tab

### ISSUE THREAD

**Issue by SevereOverfl0w** [SevereOverfl0w/Narna.me#1]

**Comment by ghost** [comment]
This would open up several more issues.

Donating and Contact would need it's own tab to, ontop of that the home page would become deserted.

A solution for that would be there if we open our prison server and display 2 images with little information on the homepage.

**Comment by SevereOverfl0w** [comment]
I mean a physical browser tab. http://www.htmlcodetutorial.com/linking/_A_TARGET_95y98y108y97y110y107y.html

**Comment by ghost** [comment]
So like a big modal for example?

**Comment by SevereOverfl0w** [comment]
Like, if you right clicked a link, and said "Open in new tab"

**Comment by ghost** [comment]
Ah, right.

**Comment by ghost** [comment]
Fixed
